### ISSUE TITLE
Team portal: Add link to Google Drive Folder into specific P/U 

### ISSUE THREAD

**Issue by florajana** [serlo-org/serlo-highrise-report#38]
To establish a better overview of P/U: Instead of only leading to the P/U overview document, the team portal page shoud also link to the entire Google drive folder of specific P/U

**Comment by SimonKoehl** [comment]
Hey ihr. In letzter Zeit kam immer wieder das Feedback, dass Leute nicht gut ihre und andere Ordner finden. Ich denke dieses issue könnte bei dem Problem sehr helfen. Vll könnt ihr es priorisieren

**Comment by kulla** [comment]
Follow up: Link shall open in a new tab with `target="_blank"`.
