### ISSUE TITLE
P/U Links in status color

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/serlo-highrise-report#40]
Suggestion: Format these links in the color of the status. This will help to decide, if a person has resources to get involved in another P/U or not.

![image](https://user-images.githubusercontent.com/3379377/39314515-b2d4869a-4974-11e8-8912-2565e61ac3d8.png)

**Comment by kulla** [comment]
Implemented by https://github.com/serlo-org/serlo-highrise-report/commit/51ed61dae0bfe83c49e36ac5199233fc9b1a33cd
