### ISSUE TITLE
mark links as P or U

### ISSUE THREAD

**Issue by SimonKoehl** [serlo-org/serlo-highrise-report#42]
You can't see if these are Projects or Units, a Person is involved in:

![image](https://user-images.githubusercontent.com/3379377/39314515-b2d4869a-4974-11e8-8912-2565e61ac3d8.png)

May be add "P_" or "U_" in front of the link?
And sort them alphabetically? (keep Lama and not Lama separated)

**Comment by kulla** [comment]
Fixed by https://github.com/illyz/serlo-highrise-report/commit/d2dd4ccf23cb85d00302da42a8ba93ee240151a2
