### ISSUE TITLE
Only show persons with overvew-data-ok tag?

### ISSUE THREAD

**Issue by kulla** [serlo-org/serlo-highrise-report#62]
Only persons shall be added who have the tag "overview-data-ok".

**Comment by illyz** [comment]
Evtl. Menschen ohne overview-data-ok tag nur mit Vornamen und ohne weitere Informationen anzeigen, so dass die Übersicht weiterhin geleistet ist.

**Comment by SimonKoehl** [comment]
Ich wiederhole mich ;) Teammitglieder müssen bereit sein, hier mit vollem Namen und mindestens einer E-Mail-Adresse gelistet zu sein.

**Comment by kulla** [comment]
BTW: Showing a `@serlo.org` adress shall be always fine.

**Comment by metzgaria** [comment]
I think this issue can be closed because the overview-data-ok tag is obsolet.

**Comment by kulla** [comment]
@metzgaria Thx for your update :-)
