### ISSUE TITLE
Add 'Status' column in 'Teammitglieder' 

### ISSUE THREAD

**Issue by illyz** [serlo-org/serlo-highrise-report#8]
Soll Stati wie Novize, Volunteer, Praktikum, Lernbegleiter etc. abbilden. Mit den aktuellen Highrise Tags glaube ich schwierig bzw kompliziert, evtl. über custom field abfragen.

**Comment by SimonKoehl** [comment]
may be leave column empty if no special status - reduce visual noice

**Comment by SimonKoehl** [comment]
redundant with #30
